### ISSUE TITLE
Swanky node cannot run with with -lerror command

### ISSUE THREAD

**Issue by vikiival** [AstarNetwork/swanky-node#40]
**Description**

I am trying to run swanky node according to tutorial:
```
./target/release/swanky-node --dev --tmp -l runtime=trace -lerror,runtime::contracts=debug
```

with this however the node cannot run.

**Workaround**:

I think that `,` is an issue

```
./target/release/swanky-node --dev --tmp -l runtime=trace -lerror-runtime::contracts=debug
```

**Environment**

> Describe the environment in which you encountered this bug. Use the list below as a starting point and add additional information if you think it's relevant.

- Operating system: MacOS 12.5.1
- Project version/tag:
- Rust version (run `rustup show`):

```
installed targets for active toolchain
--------------------------------------

aarch64-apple-darwin
wasm32-unknown-unknown

active toolchain
----------------

nightly-2022-07-24-aarch64-apple-darwin 
rustc 1.64.0-nightly (93ffde6f0 2022-07-23)
```

**Logs, Errors or Screenshots**

![Screenshot 2022-11-08 at 14 32 53](https://user-images.githubusercontent.com/22471030/200578089-97a6c25d-43b3-4d57-8194-729ba9878124.png)

**Additional Information**

> Please add any other details that you think may help us solve your problem.

**Comment by shunsukew** [comment]
It is just setting log level and filters which logs to output.


In above example,
log level `error` is set to entirely and log level `debug` is set to only runtime pallet contracts.
So if you use `ink_env::debug_println!` in your contract, node will emits debug logs.
https://use.ink/faq/#how-do-i-print-something-to-the-console-from-the-runtime

<img width="859" alt="Screen Shot 2022-11-11 at 23 52 11" src="https://user-images.githubusercontent.com/28953860/201365252-9388be47-5d86-4f22-ac8c-ffce5371bb41.png">
