### ISSUE TITLE
Offer cargo install & version bump

### ISSUE THREAD

**Issue by wottpal** [AstarNetwork/swanky-node#63]
Hey @shunsukew, two (hopefully minor things I noticed):

- [x] After your recent update to v1.6 (https://github.com/paritytech/substrate-contracts-node/issues/160) I think the package version did not get bumped (it still says 1.5 for me after installing the executable and/or installing via cargo):

```
➜  Downloads ./swanky-node --version                   
swanky-node 1.5.0-e38181f2f77
```

- [ ] first installed `swanky-node` via `cargo install swanky-node --git https://github.com/AstarNetwork/swanky-node` (because I prefer to have the executable in my global path & easily updatable. – It's the same `substrate-contracts-node` recommends in their README). It also seems to work fine first, but not if I start it with the `--dev` flag:

```
➜  swanky-node --dev             
2023-04-27 12:31:07 Swanky Node    
2023-04-27 12:31:07 ✌️  version 1.5.0-9ae9fef022e    
2023-04-27 12:31:07 ❤️  by Astar Network, 2022-2023    
2023-04-27 12:31:07 📋 Chain specification: Development    
2023-04-27 12:31:07 🏷  Node name: materialistic-mouth-9768    
2023-04-27 12:31:07 👤 Role: AUTHORITY    
2023-04-27 12:31:07 💾 Database: RocksDb at /var/folders/mg/7r1hkq8n3b19ps8l6wxwfz9h0000gn/T/substrate9EFlwT/chains/dev/db/full    
2023-04-27 12:31:07 ⛓  Native runtime: swanky-node-3 (swanky-node-1.tx1.au1)    
Error: Service(Client(VersionInvalid("cannot deserialize module: UnknownOpcode(192)")))
2023-04-27 12:31:07 Cannot create a runtime error=Other("cannot deserialize module: UnknownOpcode(192)")
```

**Comment by wottpal** [comment]
I just found this, which is probably related: https://github.com/paritytech/substrate-contracts-node/issues/178

But also via re-installing `swanky-node` via:
```
cargo install swanky-node --git https://github.com/AstarNetwork/swanky-node --force --locked
```
the problem was not fixed.

**Comment by shunsukew** [comment]
Thank you for reporting, please let me check.

**Comment by shunsukew** [comment]
Hm, I cannot reproduce the issue in my local environment.

**Comment by shunsukew** [comment]
This error comes from Wasm module deserialization.
Something related to wasm... https://github.com/paritytech/substrate/blob/16b2e644487f7f767eeefd4debf11a7948bfa4db/client/executor/common/src/runtime_blob/runtime_blob.rs#L51

**Comment by wottpal** [comment]
Yeah also found out that the issue is not directly `swanky-node` related, it also happens to fresh installs of `substrate-contracts-node`. But I found a workaround, see this comment: https://github.com/paritytech/substrate-contracts-node/issues/178#issuecomment-1525878726
